import typing as t
from _typeshed import Incomplete

class CountMinSketch:
    m: Incomplete
    d: Incomplete
    n: int
    tables: Incomplete
    def __init__(self, m: int, d: int) -> None: ...
    def add(self, x: t.Hashable, value: int = ...) -> None: ...
    def query(self, x: t.Hashable) -> int: ...
    def __getitem__(self, x: t.Hashable) -> int: ...
    def __len__(self) -> int: ...
